RMIP - MultiQC Extract docker image
RTIInternational/biocloud_docker_tools pull request #17
Opened 2023-09-01 20:01 UTC by dnwillia23

2023-09-15 16:15 UTC, jaamarks requested changes
Address comments about Dockerfile.

2023-09-15 16:15 UTC, jaamarks commented on multiqc_extract/v1.0/Dockerfile
scripts should be stored in `/opt` to follow our current design practice.

> For rtibiocloud images, the current design practice we employ is to store executables within the /opt directory of the container. This directory is also included in the PATH environment variable which stores paths to executables so that the full path to the executable does not need to be specified. The default command for rtibiocloud containers will call the usage guide for the main executable or list the executables available within /opt.

https://github.com/RTIInternational/biocloud_docker_tools/wiki/Docker-User-Guide#docker-container-conventions-for-rtibiocloud

2023-09-15 16:48 UTC, jaamarks requested changes
Instead of using just `r-base`, it's a good practice to specify a specific version of the base image to ensure reproducibility. For example, you can use `r-base:4.1.0`.

2023-09-15 18:09 UTC, jaamarks commented on multiqc_extract/v1.0/Dockerfile
install `vim` as a system requirement.

I don't understand why the R scripts are in `/data/` directory rather than the `/opt/` directory. Please explain.

Remove `# FROM arm64v8/r-base` from the top of the Dockerfile.

update your labels
**LABEL** maintainer="David Williams \<dnwilliams@rti.org\>"
**LABEL** description=` `

2023-10-06 19:42 UTC, jaamarks commented on multiqc_extract/v1.0/Dockerfile
@dnwillia23, can you address these comments?

2023-10-13 19:34 UTC, dnwillia23 commented on multiqc_extract/v1.0/Dockerfile
Changes addressed with latest commit

2023-10-13 20:01 UTC, jaamarks approved these changes
ACK

2023-10-13 20:07 UTC, merged