Initial commit: Added Dockerfile and README for Cell Ranger software
RTIInternational/biocloud_docker_tools pull request #19
Opened 2023-09-29 16:58 UTC by jaamarks

…tool.

2023-10-06 17:00 UTC, jkstratford requested changes
A few comments, do you typically try and build the docker before approving it? Or do you just trust that the developer has done this prior to submitting the pull request?

2023-10-06 17:48 UTC, jaamarks commented on cellranger/v7.2.0/Dockerfile
> +LABEL software-website="https://support.10xgenomics.com/single-cell-gene-expression/software/overview/welcome"
ACK

2023-10-06 17:49 UTC, jaamarks commented on cellranger/v7.2.0/Dockerfile
> +    && rm -rf /var/lib/apt/lists/*
ACK

2023-10-06 18:02 UTC, jaamarks commented
> A few comments, do you typically try and build the docker before approving it? Or do you just trust that the developer has done this prior to submitting the pull request?

Whoever is reviewing it should try to build the docker image before approving it. This brings up a good point though, maybe we should add a short section on **Reviewing a PR** to our https://github.com/jaamarks/biocloud_docker_tools/tree/master#dockerfile-best-practices-checklist

I'm thinking:
* **Review code**: Check for syntax errors, coding standards, and best practices.
* **Review Documentation**: Ensure that comments and READMEs are clear and informative.
* **Approve**: Verify that the Dockerfile builds locally. Then approve for merging.

2023-10-06 18:36 UTC, jaamarks commented on cellranger/v7.2.0/README.md
> +## Usage
ACK

2023-10-06 18:48 UTC, jaamarks commented on cellranger/v7.2.0/README.md
> +Because when these data are extracted the Docker image size becomes over 32GB.
ACK

2023-10-06 19:37 UTC, jaamarks commented
@jkstratford, thanks for the review. I believe I have addressed all of your comments. 
@rmathur87, would appreciate a quick review if you have time also.

2023-10-13 13:33 UTC, jkstratford approved these changes

2023-10-13 15:51 UTC, merged